export const lastProjects = [
  {
    name: 'CPD',
    projectType: 'Website',
    thumb: '/projects/cpd-website.png',
    githubLink: '',
    previewLink: 'https://www.cpd.com.br',
    stack: ['reactjs', 'nextjs', 'typescript', 'tailwindcss', 'seo'],
  },
  {
    name: 'Solaris Energia Solar',
    projectType: 'Landing page',
    thumb: '/projects/solaris-website.png',
    githubLink: '',
    previewLink: 'https://www.solaris.eco.br',
    stack: ['reactjs', 'nextjs', 'typescript', 'tailwindcss', 'seo'],
  },
  {
    name: 'Tailwind NextJs App',
    projectType: 'App',
    thumb: '/projects/tailwind-nextjs-app.png',
    githubLink: 'https://github.com/marcelopoars/tailwind-nextjs',
    previewLink: 'https://tailwind-nextjs.marcelopereira.dev',
    stack: ['reactjs', 'nextjs', 'typescript', 'tailwindcss'],
  },
  {
    name: 'Notes',
    projectType: 'App',
    thumb: '/projects/notes-nlw-expert-app.png',
    githubLink: 'https://github.com/marcelopoars/nlw-experts-notes',
    previewLink: 'https://notes.marcelopereira.dev',
    stack: ['reactjs', 'vitejs', 'typescript', 'tailwindcss'],
  },
  {
    name: 'Elaine | Costureira',
    projectType: 'Landing page',
    thumb: '/projects/elaine-costureira-website.png',
    githubLink: '',
    previewLink: 'https://www.elainecostureira.com.br',
    stack: ['reactjs', 'nextjs', 'typescript', 'tailwindcss', 'seo'],
  },
  {
    name: 'Triplo A Seminovos',
    projectType: 'Website',
    thumb: '/projects/triploa-seminovos-website.png',
    githubLink: '',
    previewLink: 'https://triploaseminovos.com.br',
    stack: ['reactjs', 'gatsbyjs', 'javascript', 'styledcomponents', 'seo'],
  },
]
