export const lastProjects = [
  {
    name: 'CPD',
    projectType: 'Website',
    thumb: '/projects/cpd-website.png',
    githubLink: '',
    previewLink: 'https://www.cpd.com.br',
    stack: ['ReactJs', 'NextJs', 'TypeScript', 'TailwindCSS', 'SEO'],
  },
  {
    name: 'Solaris Energia Solar',
    projectType: 'Landing page',
    thumb: '/projects/solaris-website.png',
    githubLink: '',
    previewLink: 'https://www.solaris.eco.br',
    stack: ['ReactJs', 'NextJs', 'TypeScript', 'TailwindCSS', 'SEO'],
  },
  {
    name: 'Tailwind NextJs',
    projectType: 'App',
    thumb: '/projects/tailwind-nextjs-app.png',
    githubLink: 'https://github.com/marcelopoars/tailwind-nextjs',
    previewLink: 'https://tailwind-nextjs.marcelopereira.dev',
    stack: ['ReactJs', 'NextJs', 'TypeScript', 'TailwindCSS'],
  },
  {
    name: 'Notes',
    projectType: 'App',
    thumb: '/projects/notes-nlw-expert-app.png',
    githubLink: 'https://github.com/marcelopoars/nlw-experts-notes',
    previewLink: 'https://notes.marcelopereira.dev',
    stack: ['ReactJs', 'Vite', 'TypeScript', 'TailwindCSS'],
  },
  {
    name: 'Elaine | Costureira',
    projectType: 'Landing page',
    thumb: '/projects/elaine-costureira-website.png',
    githubLink: '',
    previewLink: 'https://www.elainecostureira.com.br',
    stack: ['ReactJs', 'NextJs', 'TypeScript', 'TailwindCSS', 'SEO'],
  },
  {
    name: 'Triplo A Seminovos',
    projectType: 'Website',
    thumb: '/projects/triploa-seminovos-website.png',
    githubLink: '',
    previewLink: 'https://triploaseminovos.com.br',
    stack: ['ReactJs', 'GatsbyJs', 'JavaScript', 'Styled-components', 'SEO'],
  },
]
